# Generated by Django 5.2.5 on 2026-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactionmodel',
            name='product_id',
            field=models.CharField(max_length=255),
        ),
    ]
