# Generated by Django 5.2.5 on 2026-01-15 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0003_alter_transactionmodel_product_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='USD', max_length=10)),
                ('interval', models.CharField(choices=[('Week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('apple_product_id', models.CharField(blank=True, max_length=255, null=True)),
                ('google_product_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='transactionmodel',
            name='purchase_token',
            field=models.TextField(blank=True, null=True),
        ),
    ]
