# Generated by Django 5.2.5 on 2026-01-15 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_paymentplan_alter_transactionmodel_purchase_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentplan',
            name='interval',
            field=models.CharField(choices=[('trial', 'Trial'), ('Week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=20),
        ),
    ]
