# Generated by Django 5.2.5 on 2025-11-04 15:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admin_dashboard', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailOTPModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('otp', models.CharField(max_length=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_used', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LanguagePreferenceModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French')], max_length=50)),
                ('device_code', models.CharField(max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CustomUserModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('language', models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French')], default='English', max_length=50, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField(auto_now=True)),
                ('device_code', models.CharField(blank=True, max_length=100, null=True)),
                ('paid_user', models.BooleanField(default=False)),
                ('current_plan', models.CharField(choices=[('free', 'free'), ('monthly', 'monthly'), ('yearly', 'yearly')], default='free', max_length=20)),
                ('current_period_start', models.DateTimeField(blank=True, null=True)),
                ('current_period_end', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'swappable': 'AUTH_USER_MODEL',
            },
        ),
        migrations.CreateModel(
            name='ProfileEatingStyle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('Flexible', 'Flexible'), ('Balanced', 'Balanced'), ('Strict', 'Strict')], default='Balanced', max_length=20)),
                ('eating_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profile_links', to='admin_dashboard.eatingstylemodel')),
            ],
        ),
        migrations.CreateModel(
            name='ProfileModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_name', models.CharField(max_length=150)),
                ('profile_image', models.ImageField(blank=True, null=True, upload_to='')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('country', models.CharField(blank=True, max_length=100, null=True)),
                ('avatar', models.ImageField(default='https://res.cloudinary.com/dt2k6s4bg/image/upload/v1697056341/avatars/default_avatar_oqtqmb.png', upload_to='')),
                ('magic_list', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('allergies', models.ManyToManyField(blank=True, related_name='profiles', to='admin_dashboard.allergymodel')),
                ('eating_style', models.ManyToManyField(blank=True, related_name='profiles', through='users.ProfileEatingStyle', to='admin_dashboard.eatingstylemodel')),
                ('medical_conditions', models.ManyToManyField(blank=True, related_name='profiles', to='admin_dashboard.medicalconditionmodel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profiles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='profileeatingstyle',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eating_style_links', to='users.profilemodel'),
        ),
        migrations.AddConstraint(
            model_name='profilemodel',
            constraint=models.UniqueConstraint(fields=('user', 'profile_name'), name='unique_profile_per_user'),
        ),
        migrations.AlterUniqueTogether(
            name='profileeatingstyle',
            unique_together={('profile', 'eating_style')},
        ),
    ]
