# Generated by Django 5.2.5 on 2025-11-04 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languagepreferencemodel',
            name='language',
            field=models.CharField(choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Bangla', 'Bangla')], max_length=50),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.URLField(blank=True, null=True),
        ),
    ]
