# Generated by Django 5.2.5 on 2025-11-04 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_languagepreferencemodel_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='language',
            field=models.CharField(blank=True, choices=[('English', 'English'), ('Spanish', 'Spanish'), ('French', 'French'), ('Bangla', 'Bangla')], default='English', max_length=50, null=True),
        ),
    ]
