# Generated by Django 5.2.5 on 2025-11-10 18:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_customusermodel_language'),
    ]

    operations = [
        migrations.DeleteModel(
            name='LanguagePreferenceModel',
        ),
        migrations.RemoveField(
            model_name='customusermodel',
            name='device_code',
        ),
    ]
