# Generated by Django 5.2.5 on 2025-11-25 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_responses', '0004_remove_myplatemodel_description_and_more'),
        ('users', '0004_delete_languagepreferencemodel_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilemodel',
            name='my_platters',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_platter', to='ai_responses.myplatemodel'),
        ),
    ]
