# Generated by Django 5.2.5 on 2025-11-25 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profilemodel_my_platters'),
    ]

    operations = [
        migrations.AddField(
            model_name='customusermodel',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
