# Generated by Django 5.2.5 on 2026-01-03 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_fix_missing_language_column'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customusermodel',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='country',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='profilemodel',
            name='profile_image',
            field=models.ImageField(blank=True, max_length=2048, null=True, upload_to=''),
        ),
    ]
