# Generated by Django 5.2.5 on 2026-01-03 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_customusermodel_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilemodel',
            name='avatar',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
