# Generated by Django 5.2.5 on 2025-11-10 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedbackmodel',
            name='name',
        ),
    ]
