# Generated by Django 5.2.5 on 2025-11-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0002_remove_feedbackmodel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='eatingstylemodel',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
    ]
