# Generated by Django 5.2.5 on 2025-11-17 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_eatingstylemodel_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalconditionmodel',
            name='medical_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
