# Generated by Django 5.2.5 on 2026-01-01 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_medicalconditionmodel_medical_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allergymodel',
            name='allergy_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='eatingstylemodel',
            name='eating_style_name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='medicalconditionmodel',
            name='medical_condition_name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
