# Generated by Django 5.2.5 on 2026-01-02 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_alter_allergymodel_allergy_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eatingstylemodel',
            name='eating_style_name',
            field=models.TextField(unique=True),
        ),
    ]
