# Generated by Django 5.2.5 on 2026-01-03 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0007_alter_aboutusmodel_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutusmodel',
            name='image',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='allergymodel',
            name='allergy_icon',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='avatarmodel',
            name='avatar_icon',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='eatingstylemodel',
            name='eating_style_icon',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='medicalconditionmodel',
            name='medical_condition_icon',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='privacypolicymodel',
            name='image',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
        migrations.AlterField(
            model_name='termsandconditionsmodel',
            name='image',
            field=models.URLField(blank=True, max_length=2048, null=True),
        ),
    ]
