# Generated by Django 5.2.5 on 2025-11-10 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_responses', '0003_myplatemodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myplatemodel',
            name='description',
        ),
        migrations.AddField(
            model_name='myplatemodel',
            name='meal_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myplatemodel',
            name='plate_combo',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
