# Generated by Django 5.2.5 on 2026-01-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_responses', '0004_remove_myplatemodel_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scanneddocumentmodel',
            name='file_url',
        ),
        migrations.AddField(
            model_name='scanneddocumentmodel',
            name='file_urls',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
